### ISSUE TITLE
Jamf Pro SSO Support

### ISSUE THREAD

**Issue by vazome** [jamf/mut#104]
SSO enabled admins are unable to login into MUT. Would be a good feature to add.

**Comment by tranziq** [comment]
Confirmed.    Logs show that APIs are not being authenticated by SSO users

2023-04-03 11:02:04 [INFO  ]: Submitting a PUT to https://myjamfserver.com/JSSResource/computers/serialnumber/C02***********
2023-04-03 11:02:04 [ERROR ]: Failed PUT. 401.
2023-04-03 11:02:04 [ERROR ]: <html>
<head>
	<title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Unauthorized</p>
<p>The request requires user authentication</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br>
	Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

**Comment by brandonrcampbell** [comment]
following - also would love this ability.

**Comment by acheeseburgerplease** [comment]
Same. Unable to get MUT to login into our Jamf server due to Google SSO.

**Comment by mikelevenick** [comment]
Unfortunately, this is an API limitation and not something we are able to implement. If that changes in the future, we will reopen. Thanks!
