### ISSUE TITLE
Allow main window to be resized, at least vertically...

### ISSUE THREAD

**Issue by bradchapman-nbcu** [jamf/mut#76]
Love the new version.  Could you allow us to resize the window please?  

I am mass-updating a "pop-up menu" EA, and this field requires me to scroll down to verify the value in MUTv6.

Thanks!

**Comment by mike-levenick** [comment]
To be totally honest, I really doubt a dynamic sizing option is in the future for this iteration of MUT. I might be wrong, but I suspect that the table view aspect of the UI is just too brittle in its current format.

That said, I do plan to, at the very least, make the window bigger so you can see everything in the CSV--and a few extra rows for EAs as well. I'll chat with Ben who did some work on the UI and see what he thinks as well.

**Comment by bradtchapman** [comment]
@mikelevenick, nice.  Bringing closure to an unresolved issue.

How you been?

**Comment by mikelevenick** [comment]
haha Hey! Yeah, going through and cleaning up Issues here.. they got a bit out of hand. Doing well. 

One thing I've considered is a ground-up rebuild of MUT in SwiftUI which would make something like this trivial, but in its current state, I just don't think it's feasible.

Hope to see you at JNUC this year if I get a chance to go!
